# netlify.toml

# Detta är en "redirect rule". Den omdirigerar ALLA sökvägar som inte kan hittas
# till /index.html och returnerar en HTTP 200 (OK) status.
# Detta låter Vue Router ta över och hantera routingen.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Aktiverar Netlifys prerendering-tjänst.
# Detta serverar en cachad, fullständigt renderad HTML-version av sidan
# till specificerade user agents (sökmotor-bots), vilket är kritiskt
# för SEO i en Single-Page Application.
[prerender]
  enable = true

# NYTT OCH AVGÖRANDE: Konfigurerar Netlify att ignorera builds om endast vissa filer ändras.
# Byggprocessen triggas ENDAST om det finns ändringar i:
# - FILEN 'buildtrigger.txt'
# Alla andra ändringar i REPOSITORYT (oavsett mapp eller fil) kommer att ignoreras.
# För att deploya, måste du manuellt ändra 'buildtrigger.txt' och pusha den.
[build]
  ignore = "git diff --quiet HEAD^ HEAD -- . 'buildtrigger.txt'"
