# netlify.toml

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[prerender]
  enable = true

# RIKTIG KORRIGERING:
# Detta skript kollar om buildtrigger.txt finns bland de ändrade filerna.
# Om den INTE finns, returnerar skriptet exit code 0 (-> ignorera bygge).
# Om den FINNS, returnerar skriptet exit code 1 (-> starta bygge).
[build]
  ignore = "bash -c 'git diff --name-only HEAD^ HEAD | grep -q buildtrigger.txt && exit 1 || exit 0'"
