# This is the configuration file for Cloudflare Workers and Pages.

# The name of your application.
name = "engrove"

# The date of the Workers runtime version to use.
# It's good practice to set this to the current date when you create the project.
compatibility_date = "2025-07-16"

# This section is crucial for Cloudflare Pages.
# It tells Wrangler that this is a Pages project and where the static assets are.
[pages]
main.dir = "dist"
