# This is the configuration file for Cloudflare Pages.

# The name of your Pages project.
name = "engrove"

# The date of the Workers runtime version to use.
compatibility_date = "2025-07-16"

# [pages]-sektionen är nu borttagen. Istället specificerar vi byggkonfigurationen direkt.
# Detta är den föredragna metoden som Cloudflare Pages nu letar efter.
[pages_build_output_dir]
main = "dist"
