# This is the configuration file for Cloudflare Pages.

# The name of your Pages project.
name = "engrove"

# The date of the Workers runtime version to use.
compatibility_date = "2025-07-16"

# This property tells Cloudflare Pages which directory contains the finished site.
# It should be a simple string.
pages_build_output_dir = "dist"
