<!-- src/views/ReportView.vue -->
<template>
  <div class="report-wrapper">
    <header class="report-header">
      <h1>{{ reportTitle }}</h1>
      <p>Generated by Engrove Audio Toolkit on {{ generationDate }}</p>
      <button @click="printReport" class="print-button">Print or Save as PDF</button>
    </header>

    <main class="report-content" v-if="reportData && !reportData.error">
      <!-- Sektion för Tonarmskalkylatorn -->
      <section v-if="reportData.type === 'tonearm'" class="report-section">
        <h2>Tonearm Resonance Calculation</h2>
        <div class="data-grid">
          <div class="data-group">
            <h3>Input Parameters</h3>
            <ul>
              <li v-if="reportData.params.calculationMode === 'detailed'" v-for="param in tonearmParamsDetailed.filter(p => reportData.params[p.key] !== null)" :key="param.key">
                <strong>{{ param.label }}:</strong>
                <span>{{ reportData.params[param.key] }} {{ param.unit }}</span>
              </li>
              <li v-if="reportData.params.calculationMode === 'direct'" v-for="param in tonearmParamsDirect.filter(p => reportData.params[p.key] !== null)" :key="param.key">
                <strong>{{ param.label }}:</strong>
                <span>{{ reportData.params[param.key] }} {{ param.unit }}</span>
              </li>
            </ul>
          </div>
          <div class="data-group">
            <h3>Calculated Results</h3>
            <ul>
              <li v-if="reportData.results.isUnbalanced && reportData.params.calculationMode === 'detailed'"><strong>Status:</strong> <span class="danger-text">Unbalanced</span></li>
              <li v-if="!reportData.results.isUnbalanced || reportData.params.calculationMode === 'direct'"><strong>Effective Mass:</strong> <span>{{ reportData.results.M_eff.toFixed(1) }} g</span></li>
              <li v-if="!reportData.results.isUnbalanced || reportData.params.calculationMode === 'direct'"><strong>Resonance Frequency:</strong> <span class="final-result">{{ reportData.results.F.toFixed(1) }} Hz</span></li>
            </ul>
            <div v-if="!reportData.results.isUnbalanced || reportData.params.calculationMode === 'direct'" class="diagnosis-box" :class="reportData.diagnosis.status">
              <h4>{{ reportData.diagnosis.title }}</h4>
              <p>{{ reportData.diagnosis.recommendations.join(' ') }}</p>
            </div>
          </div>
        </div>
      </section>

      <!-- Sektion för Compliance Estimator -->
      <section v-if="reportData.type === 'estimator'" class="report-section">
        <h2>Compliance Estimation</h2>
         <div class="data-grid">
          <div class="data-group">
            <h3>Input Specifications</h3>
            <ul>
               <li v-for="param in estimatorParams.filter(p => reportData.userInput[p.key] !== null && reportData.userInput[p.key] !== '')" :key="param.key">
                <strong>{{ param.label }}:</strong>
                <span>{{ reportData.userInput[param.key] }}</span>
              </li>
            </ul>
          </div>
          <div class="data-group">
            <h3>Estimated Result</h3>
            <div class="main-result">
              <div class="result-value">
                {{ resultRange }}
                <span>µm/mN @ 10Hz</span>
              </div>
              <p v-if="showMedianNote" class="median-note">(Median Estimate: {{ reportData.result.compliance_median.toFixed(1) }})</p>
            </div>
            <div class="diagnosis-box" :class="confidenceClass">
                <h4>Confidence: {{ confidenceLevel }} ({{ reportData.result.confidence }}%)</h4>
                <p>{{ reportData.result.description }} (Sample size: {{ reportData.result.sampleSize }})</p>
            </div>
          </div>
        </div>
      </section>
    </main>
    <main v-else class="report-content">
        <h2>Error</h2>
        <p>Could not load report data. Please return to the previous page and try again.</p>
    </main>

    <footer class="report-footer">
      <p><strong>Disclaimer:</strong> This report is a theoretical calculation for educational and hobbyist purposes. Always verify with real-world measurements. Engrove Audio Toolkit assumes no liability for its use.</p>
    </footer>
  </div>
</template>

<script setup>
import { ref, onMounted, computed } from 'vue';
import { useRoute } from 'vue-router';

const route = useRoute();
const reportData = ref(null);
const reportTitle = ref("Report");
const generationDate = new Date().toLocaleString();

const printReport = () => window.print();

onMounted(() => {
  try {
    const decodedData = JSON.parse(atob(route.query.data));
    reportData.value = decodedData;
    reportTitle.value = decodedData.type === 'tonearm' ? 'Tonearm Resonance Report' : 'Compliance Estimation Report';
  } catch (e) {
    console.error("Failed to parse report data:", e);
    reportData.value = { error: "Invalid data provided." };
    reportTitle.value = "Error";
  }
});

// Tonearm-specifik data
const tonearmParamsDetailed = ref([
  { key: 'm_headshell', label: 'Headshell Mass', unit: 'g' },
  { key: 'm_pickup', label: 'Cartridge Mass', unit: 'g' },
  { key: 'm_screws', label: 'Screws Mass', unit: 'g' },
  { key: 'compliance', label: 'Compliance @ 10Hz', unit: 'cu' },
  { key: 'vtf', label: 'Tracking Force', unit: 'g' },
  { key: 'L1', label: 'Effective Length', unit: 'mm' },
  { key: 'm_rear_assembly', label: 'Rear Assembly Mass', unit: 'g'},
  { key: 'm4_adj_cw', label: 'Adjustable CW Mass', unit: 'g' },
]);
const tonearmParamsDirect = ref([
  { key: 'm_pickup', label: 'Cartridge Mass', unit: 'g' },
  { key: 'compliance', label: 'Compliance @ 10Hz', unit: 'cu' },
  { key: 'directEffectiveMass', label: 'Tonearm Effective Mass', unit: 'g' }
]);

// Estimator-specifik data
const estimatorParams = ref([
    { key: 'cu_dynamic_100hz', label: 'Compliance @ 100Hz' },
    { key: 'cu_static', label: 'Static Compliance' },
    { key: 'type', label: 'Pickup Type' },
    { key: 'cantilever_class', label: 'Cantilever Class' },
    { key: 'stylus_family', label: 'Stylus Family' },
]);

const resultRange = computed(() => {
    if (!reportData.value || reportData.value.type !== 'estimator' || !reportData.value.result.compliance_median) return '--';
    const { compliance_min, compliance_median, compliance_max } = reportData.value.result;
    if (compliance_min && compliance_max && compliance_min.toFixed(1) !== compliance_max.toFixed(1)) {
        return `${compliance_min.toFixed(1)} – ${compliance_max.toFixed(1)}`;
    }
    return compliance_median.toFixed(1);
});

const showMedianNote = computed(() => {
    if (!reportData.value || reportData.value.type !== 'estimator' || !reportData.value.result.compliance_median) return false;
    const { compliance_min, compliance_max } = reportData.value.result;
    return compliance_min && compliance_max && compliance_min.toFixed(1) !== compliance_max.toFixed(1);
});

const confidenceLevel = computed(() => {
    if (!reportData.value || reportData.value.type !== 'estimator') return 'N/A';
    const conf = reportData.value.result.confidence;
    if (conf >= 80) return 'High';
    if (conf >= 60) return 'Medium';
    return 'Low';
});

const confidenceClass = computed(() => {
    if (!reportData.value || reportData.value.type !== 'estimator') return '';
    const conf = reportData.value.result.confidence;
    if (conf >= 80) return 'ideal';
    if (conf >= 60) return 'warning';
    return 'danger';
});

</script>
