<!-- src/views/ReportView.vue -->
<template>
  <div class="report-wrapper">
    <header class="report-header">
      <h1>{{ reportTitle }}</h1>
      <p>Generated by Engrove Audio Toolkit on {{ generationDate }}</p>
      <button @click="printReport" class="print-button">Print or Save as PDF</button>
    </header>

    <main class="report-content" v-if="reportData && !reportData.error">
      <!-- Sektion för Tonarmskalkylatorn -->
      <section v-if="reportData.type === 'tonearm'" class="report-section">
        <h2>Tonearm Resonance Calculation</h2>
        <div class="data-grid">
          <div class="data-group">
            <h3>Input Parameters</h3>
            <ul>
              <li v-if="reportData.params.calculationMode === 'detailed'" v-for="param in tonearmParamsDetailed.filter(p => reportData.params[p.key] !== null)" :key="param.key">
                <strong>{{ param.label }}:</strong>
                <span>{{ reportData.params[p.key] }} {{ param.unit }}</span>
              </li>
              <li v-if="reportData.params.calculationMode === 'direct'" v-for="param in tonearmParamsDirect.filter(p => reportData.params[p.key] !== null)" :key="param.key">
                <strong>{{ param.label }}:</strong>
                <span>{{ reportData.params[p.key] }} {{ param.unit }}</span>
              </li>
            </ul>
          </div>
          <div class="data-group">
            <h3>Calculated Results</h3>
            <ul>
              <li v-if="reportData.results.isUnbalanced && reportData.params.calculationMode === 'detailed'"><strong>Status:</strong> <span class="danger-text">Unbalanced</span></li>
              <li v-if="!reportData.results.isUnbalanced || reportData.params.calculationMode === 'direct'"><strong>Effective Mass:</strong> <span>{{ reportData.results.M_eff.toFixed(1) }} g</span></li>
              <li v-if="!reportData.results.isUnbalanced || reportData.params.calculationMode === 'direct'"><strong>Resonance Frequency:</strong> <span class="final-result">{{ reportData.results.F.toFixed(1) }} Hz</span></li>
            </ul>
            <div v-if="!reportData.results.isUnbalanced || reportData.params.calculationMode === 'direct'" class="diagnosis-box" :class="reportData.diagnosis.status">
              <h4>{{ reportData.diagnosis.title }}</h4>
              <p>{{ reportData.diagnosis.recommendations.join(' ') }}</p>
            </div>
          </div>
        </div>
      </section>

      <!-- Sektion för Compliance Estimator -->
      <section v-if="reportData.type === 'estimator'" class="report-section">
        <h2>Compliance Estimation</h2>
         <div class="data-grid">
          <div class="data-group">
            <h3>Input Specifications</h3>
            <ul>
               <li v-for="param in estimatorParams.filter(p => reportData.userInput[p.key] !== null && reportData.userInput[p.key] !== '')" :key="param.key">
                <strong>{{ param.label }}:</strong>
                <span>{{ reportData.userInput[p.key] }}</span>
              </li>
            </ul>
          </div>
          <div class="data-group">
            <h3>Estimated Result</h3>
            <div class="main-result">
              <div class="result-value">
                {{ resultRange }}
                <span>µm/mN @ 10Hz</span>
              </div>
              <p v-if="showMedianNote" class="median-note">(Median Estimate: {{ reportData.result.compliance_median.toFixed(1) }})</p>
            </div>
            <div class="diagnosis-box" :class="confidenceClass">
                <h4>Confidence: {{ confidenceLevel }} ({{ reportData.result.confidence }}%)</h4>
                <p>{{ reportData.result.description }} (Sample size: {{ reportData.result.sampleSize }})</p>
            </div>
          </div>
        </div>
      </section>
    </main>
    <main v-else class="report-content">
        <h2>Error</h2>
        <p>Could not load report data. Please return to the previous page and try again.</p>
    </main>

    <!-- NY DISCLAIMER-SEKTION -->
    <footer class="report-footer">
      <h3>Disclaimer</h3>
      <p>This report is provided as a design aid for theoretical exploration and educational purposes only. The calculations are based on established physical principles but are the product of a hobbyist project. Data is compiled from publicly available sources.</p>
      <p>While every effort is made to verify accuracy, there is no guarantee of the absolute correctness of the data or calculations. Users are encouraged to cross-reference the results with their own measurements and practical experience. The ultimate responsibility for any physical build or component matching rests with the user.</p>
    </footer>
  </div>
</template>

<script setup>
import { ref, onMounted, computed } from 'vue';
import { useRoute } from 'vue-router';

const route = useRoute();
const reportData = ref(null);
const reportTitle = ref("Report");
const generationDate = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

const printReport = () => window.print();

onMounted(() => {
  try {
    const decodedData = JSON.parse(atob(route.query.data));
    reportData.value = decodedData;
    reportTitle.value = decodedData.type === 'tonearm' ? 'Tonearm Resonance Report' : 'Compliance Estimation Report';
  } catch (e) {
    console.error("Failed to parse report data:", e);
    reportData.value = { error: "Invalid data provided." };
    reportTitle.value = "Error";
  }
});

// Tonearm-specifik data
const tonearmParamsDetailed = ref([
  { key: 'm_headshell', label: 'Headshell Mass', unit: 'g' },
  { key: 'm_pickup', label: 'Cartridge Mass', unit: 'g' },
  { key: 'm_screws', label: 'Screws Mass', unit: 'g' },
  { key: 'compliance', label: 'Compliance @ 10Hz', unit: 'cu' },
  { key: 'vtf', label: 'Tracking Force', unit: 'g' },
  { key: 'L1', label: 'Effective Length', unit: 'mm' },
  { key: 'm_rear_assembly', label: 'Rear Assembly Mass', unit: 'g'},
  { key: 'm4_adj_cw', label: 'Adjustable CW Mass', unit: 'g' },
]);
const tonearmParamsDirect = ref([
  { key: 'm_pickup', label: 'Cartridge Mass', unit: 'g' },
  { key: 'compliance', label: 'Compliance @ 10Hz', unit: 'cu' },
  { key: 'directEffectiveMass', label: 'Tonearm Effective Mass', unit: 'g' }
]);

// Estimator-specifik data
const estimatorParams = ref([
    { key: 'cu_dynamic_100hz', label: 'Compliance @ 100Hz' },
    { key: 'cu_static', label: 'Static Compliance' },
    { key: 'type', label: 'Pickup Type' },
    { key: 'cantilever_class', label: 'Cantilever Class' },
    { key: 'stylus_family', label: 'Stylus Family' },
]);

const resultRange = computed(() => {
    if (!reportData.value || reportData.value.type !== 'estimator' || !reportData.value.result.compliance_median) return '--';
    const { compliance_min, compliance_median, compliance_max } = reportData.value.result;
    if (compliance_min && compliance_max && compliance_min.toFixed(1) !== compliance_max.toFixed(1)) {
        return `${compliance_min.toFixed(1)} – ${compliance_max.toFixed(1)}`;
    }
    return compliance_median.toFixed(1);
});

const showMedianNote = computed(() => {
    if (!reportData.value || reportData.value.type !== 'estimator' || !reportData.value.result.compliance_median) return false;
    const { compliance_min, compliance_max } = reportData.value.result;
    return compliance_min && compliance_max && compliance_min.toFixed(1) !== compliance_max.toFixed(1);
});

const confidenceLevel = computed(() => {
    if (!reportData.value || reportData.value.type !== 'estimator') return 'N/A';
    const conf = reportData.value.result.confidence;
    if (conf >= 80) return 'High';
    if (conf >= 60) return 'Medium';
    return 'Low';
});

const confidenceClass = computed(() => {
    if (!reportData.value || reportData.value.type !== 'estimator') return '';
    const conf = reportData.value.result.confidence;
    if (conf >= 80) return 'ideal';
    if (conf >= 60) return 'warning';
    return 'danger';
});
</script>

<style scoped>
.report-wrapper {
  max-width: 800px;
  margin: 0 auto;
  padding: 2rem;
  background-color: #fff;
}

.report-header {
  text-align: center;
  border-bottom: 2px solid #333;
  padding-bottom: 1rem;
  margin-bottom: 2rem;
}

.report-header h1 {
  margin: 0;
  color: #333;
}

.report-header p {
  margin: 0.5rem 0;
  color: #555;
  font-style: italic;
}

.report-section {
  margin-bottom: 2.5rem;
}
.report-section h2 {
  font-size: 1.5rem;
  color: var(--header-color);
  border-bottom: 1px solid var(--border-color);
  padding-bottom: 0.5rem;
  margin-bottom: 1.5rem;
}

.data-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  gap: 2rem;
}

.data-group h3 {
  font-size: 1.2rem;
  color: var(--accent-color);
  margin-top: 0;
  margin-bottom: 1rem;
}

.data-group ul {
  list-style: none;
  padding: 0;
  margin: 0;
}

.data-group li {
  display: flex;
  justify-content: space-between;
  padding: 0.5rem 0;
  border-bottom: 1px solid #eee;
}

.data-group li strong {
  color: var(--label-color);
}

.final-result {
  font-weight: bold;
  font-size: 1.1em;
}

.danger-text {
  color: var(--danger-text);
  font-weight: bold;
}

.diagnosis-box {
  margin-top: 1rem;
  padding: 1rem;
  border-radius: 6px;
  border-left-width: 5px;
  border-left-style: solid;
}
.diagnosis-box.ideal { background-color: var(--ideal-color); border-color: #155724; }
.diagnosis-box.warning { background-color: var(--warning-color); border-color: #856404; }
.diagnosis-box.danger { background-color: var(--danger-color); border-color: #721c24; }
.diagnosis-box h4 { margin: 0 0 0.5rem 0; }
.diagnosis-box p { margin: 0; }

.main-result {
  text-align: center;
  margin-bottom: 1rem;
}
.result-value {
  font-size: 2.5rem;
  font-weight: bold;
  color: var(--header-color);
}
.result-value span {
  font-size: 1.2rem;
  font-weight: normal;
  color: var(--label-color);
  margin-left: 0.5rem;
}
.median-note {
  font-style: italic;
  color: #666;
}

.report-footer {
  margin-top: 3rem;
  padding-top: 1.5rem;
  border-top: 2px solid #333;
  font-size: 0.8rem;
  color: #666;
  text-align: center;
}
.report-footer h3 {
    margin-top: 0;
}
</style>
